application: rideshare-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: main.app
- url: /notifications/check
- url: /recurring/check
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

