application: rideshare-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: django
  version: "1.2"

# builtins:
# - remote_api: on
# - datastore_admin: on

# handlers:
# - url: /static
#   static_dir: static

# - url: /.*
#   script: main.py

